from __future__ import annotations

from typing import Any


def collect_config(gui: Any) -> dict[str, object]:
    return {
        "window_geometry": gui._current_window_geometry(),
        "work_folder": gui.work_folder_var.get().strip(),
        "scene_input": gui.scene_input_var.get().strip(),
        "scene_detector": gui.scene_detector_var.get().strip(),
        "scene_threshold": gui.scene_threshold_var.get().strip(),
        "scene_backend": gui.scene_backend_var.get().strip(),
        "scene_crop_mode": gui.scene_crop_mode_var.get().strip(),
        "scene_crop_custom": gui.scene_crop_custom_var.get().strip(),
        "scene_crop_target_h": gui.scene_crop_target_h_var.get().strip(),
        "scene_layout": gui.scene_layout_var.get().strip(),
        "scene_tonemap": gui.scene_tonemap_var.get().strip(),
        "scene_codec": gui.scene_codec_var.get().strip(),
        "global_encoder_mode": gui._current_global_encoder_mode(),
        "global_ffmpeg_extra_args": gui._current_global_ffmpeg_extra_args(),
        "depth_mode": gui.depth_mode_var.get().strip(),
        "depth_chunk_size": gui.depth_chunk_size_var.get().strip(),
        "depth_overlap": gui.depth_overlap_var.get().strip(),
        "depth_inference_steps": gui.depth_inference_steps_var.get().strip(),
        "depth_cpu_offload": gui.depth_cpu_offload_var.get().strip(),
        "depth_seed": gui.depth_seed_var.get().strip(),
        "depth_guidance_scale": gui.depth_guidance_scale_var.get().strip(),
        "depth_decode_chunk_size": gui.depth_decode_chunk_size_var.get().strip(),
        "depth_restart_every": gui.depth_restart_every_var.get().strip(),
        "depth_debug_mem": bool(gui.depth_debug_mem_var.get()),
        "depth_glob": gui.depth_glob_var.get().strip(),
        "depth_runtime_mode": gui._normalize_depth_runtime_mode(
            gui.depth_runtime_mode_var.get()
        ),
        "depth_worker_script": gui.depth_worker_script_var.get().strip(),
        "depth_scale_factor": f"{gui._get_depth_scale_factor():.2f}",
        "depth_res_x": gui.depth_res_x_var.get().strip(),
        "depth_res_y": gui.depth_res_y_var.get().strip(),
        "depth_codec": gui.depth_codec_var.get().strip(),
        "splat_mode": gui.splat_mode_var.get().strip(),
        "splat_batch_size": gui.splat_batch_size_var.get().strip(),
        "splat_workers": gui.splat_workers_var.get().strip(),
        "splat_disparity": gui.splat_disparity_var.get().strip(),
        "splat_layout": gui.splat_layout_var.get().strip(),
        "splat_auto_convergence": gui.splat_auto_convergence_var.get().strip(),
        "splat_dilate_x": gui.splat_dilate_x_var.get().strip(),
        "splat_dilate_y": gui.splat_dilate_y_var.get().strip(),
        "splat_blur_x": gui.splat_blur_x_var.get().strip(),
        "splat_blur_y": gui.splat_blur_y_var.get().strip(),
        "splat_dilate_left": gui.splat_dilate_left_var.get().strip(),
        "splat_blur_balance": gui.splat_blur_balance_var.get().strip(),
        "splat_gamma": gui.splat_gamma_var.get().strip(),
        "splat_convergence": gui.splat_convergence_var.get().strip(),
        "splat_stair_smooth": bool(gui.splat_stair_smooth_var.get()),
        "splat_stair_kernel": gui.splat_stair_kernel_var.get().strip(),
        "splat_stair_x_off": gui.splat_stair_x_off_var.get().strip(),
        "splat_stair_strip": gui.splat_stair_strip_var.get().strip(),
        "splat_stair_strength": gui.splat_stair_strength_var.get().strip(),
        "splat_replace_mask": bool(gui.splat_replace_mask_var.get()),
        "splat_replace_mask_scale": gui.splat_replace_mask_scale_var.get().strip(),
        "splat_replace_mask_min": gui.splat_replace_mask_min_var.get().strip(),
        "splat_replace_mask_max": gui.splat_replace_mask_max_var.get().strip(),
        "splat_replace_mask_gap": gui.splat_replace_mask_gap_var.get().strip(),
        "splat_replace_mask_edge": bool(gui.splat_replace_mask_edge_var.get()),
        "splat_codec": gui.splat_codec_var.get().strip(),
        "inpaint_mode": gui.inpaint_mode_var.get().strip(),
        "inpaint_frames_chunk": gui._get_inpaint_chunk_manual_value(),
        "inpaint_dynamic_chunk": bool(gui.inpaint_dynamic_chunk_var.get()),
        "inpaint_cpu_offload": gui.inpaint_cpu_offload_var.get().strip(),
        "inpaint_tile_mode": gui.inpaint_tile_mode_var.get().strip(),
        "inpaint_tile1_max_size": gui.inpaint_tile1_max_size_var.get().strip(),
        "inpaint_tile2_max_size": gui.inpaint_tile2_max_size_var.get().strip(),
        "inpaint_dynamic_visible_chunk_steps5": gui.inpaint_dynamic_visible_chunk_steps5_var.get().strip(),
        "inpaint_dynamic_visible_chunk_steps6": gui.inpaint_dynamic_visible_chunk_steps6_var.get().strip(),
        "inpaint_dynamic_visible_chunk_steps7": gui.inpaint_dynamic_visible_chunk_steps7_var.get().strip(),
        "inpaint_dynamic_visible_chunk_steps8_plus": gui.inpaint_dynamic_visible_chunk_steps8_plus_var.get().strip(),
        "inpaint_dynamic_hold_divisor": gui.inpaint_dynamic_hold_divisor_var.get().strip(),
        "inpaint_input_bias": gui.inpaint_input_bias_var.get().strip(),
        "inpaint_overlap": gui.inpaint_overlap_var.get().strip(),
        "inpaint_tail_pad": gui.inpaint_tail_pad_var.get().strip(),
        "inpaint_use_sharpness_csv": bool(gui.inpaint_use_sharpness_csv_var.get()),
        "inpaint_dynamic_resolution": bool(gui.inpaint_dynamic_resolution_var.get()),
        "inpaint_resolution_limit": gui.inpaint_resolution_limit_var.get().strip(),
        "inpaint_sharpness_workers": gui.inpaint_sharpness_workers_var.get().strip(),
        "inpaint_use_sharpen": bool(gui.inpaint_use_sharpen_var.get()),
        "inpaint_sharpen_workers": gui.inpaint_sharpen_workers_var.get().strip(),
        "inpaint_inference_steps": gui.inpaint_inference_steps_var.get().strip(),
        "inpaint_codec": gui.inpaint_codec_var.get().strip(),
        "merge_mode": gui.merge_mode_var.get().strip(),
        "merge_autoct_workers": gui.merge_autoct_workers_var.get().strip(),
        "merge_mask_formerge_workers": gui.merge_mask_formerge_workers_var.get().strip(),
        "merge_parallel": bool(gui._get_merge_worker_count() >= 2),
        "merge_parallel_workers": gui.merge_parallel_workers_var.get().strip(),
        "merge_use_gpu": bool(gui.merge_use_gpu_var.get()),
        "merge_output_format": gui.merge_output_format_var.get().strip(),
        "merge_chunks": gui.merge_chunks_var.get().strip(),
        "merge_mask_binarize": gui.merge_mask_binarize_var.get().strip(),
        "merge_mask_dilate": gui.merge_mask_dilate_var.get().strip(),
        "merge_mask_blur": gui.merge_mask_blur_var.get().strip(),
        "merge_shadow_length": gui.merge_shadow_length_var.get().strip(),
        "merge_shadow_curve": gui.merge_shadow_curve_var.get().strip(),
        "merge_dynamic_shadow_width": bool(gui.merge_dynamic_shadow_width_var.get()),
        "merge_use_replace_mask": bool(gui.merge_use_replace_mask_var.get()),
        "merge_ct_preset": gui.merge_ct_preset_var.get().strip(),
        "merge_ct_auto_mode": gui.merge_ct_auto_mode_var.get().strip(),
        "merge_ct_exclude_black": bool(gui.merge_ct_exclude_black_var.get()),
        "merge_codec": gui.merge_codec_var.get().strip(),
        "join_mode": gui.join_mode_var.get().strip(),
        "join_encoder": gui.join_encoder_var.get().strip(),
        "join_crf": gui.join_crf_var.get().strip(),
        "join_preset": gui.join_preset_var.get().strip(),
        "join_pix_fmt": gui.join_pix_fmt_var.get().strip(),
        "join_extra_args": gui.join_extra_args_var.get().strip(),
        "scene_split_threads": gui.scene_split_threads_var.get().strip(),
        "verify_scenes_workers": gui.verify_scenes_workers_var.get().strip(),
        "pipeline_verify_after": gui.pipeline_verify_after_var.get().strip(),
        "pipeline_test_run_files": gui.pipeline_test_run_files_var.get().strip(),
        "depth_retry_policy": gui._collect_retry_policy_config_from_vars(
            gui.depth_retry_policy_vars
        ),
        "inpaint_retry_policy": gui._collect_retry_policy_config_from_vars(
            gui.inpaint_retry_policy_vars
        ),
        "resume_enabled": bool(gui.resume_enabled_var.get()),
        "stop_on_error": bool(gui.stop_on_error_var.get()),
        "auto_advance": bool(gui.auto_advance_var.get()),
    }
